name: Static Site

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: List contents of working directory
        run: |
          ls -l
      # build you static site here if needed
      # - id: 'build'
      #   name: 'Build'
      #   run: |
      #     hugo --gc --minify


      # configure gcloud `setup-gcloud` automatically
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/564830921192/locations/global/workloadIdentityPools/github2/providers/my-repo2'
          #workload_identity_provider: 'projects/143616246873/locations/global/workloadIdentityPools/pool-thingy/providers/<YOUR PROVIDER HERE>'
          service_account: 'service-thingy@cs1660-project-407813.iam.gserviceaccount.com' 

      # upload files to GCS
      - name: List contents of working directory
        run: |
          ls -l

      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'https://storage.googleapis.com/bucket1660/index.html' # UPDATE THIS TO YOUR BUILD/FILES DIRECTORY
          destination: 'bucket1660' 
          parent: false

